### ISSUE TITLE
[NOT AN ISSUE!] hey mate, you got discord?

### ISSUE THREAD

**Issue by xspyy** [rscwn/MobileBloxV2#1]
hey gng, i saw you made that other roblox android exec and i was really mind-blown when i saw how it worked and how to hook into the main library, i've had problems trying to build it and i gave up on trying to build the project into a .so file (gradle cant compile into .so files 💀). Now that you came back with a new and proper roblox android executor, wanna add me in discord?

i do a little bit of c++ (i got knowledge of gamehacking) and all these other shit heads, i eventually made a page decryptor for byfron (the code is aids 😭😭).

and yeah, just wanted to tell you seem smart as fuck and has good knowledge of roblox android's process.

add me in discord *if you want* : xspyy (or by userid): 1118630070400073870

**Comment by rscwn** [comment]
Yeah, noppedout#0

**Comment by xspyy** [comment]
> Yeah, noppedout#0

thanks mate
